/**
 * PDF generation utilities
 * This is a stub implementation - in production, use puppeteer or a similar library
 */

import { MonthlyProjection, ProjectionSummary } from "@/lib/types";

export interface PDFExportOptions {
  projections: MonthlyProjection[];
  summary: ProjectionSummary;
  companyName: string;
  scenarioName: string;
  includeCharts?: boolean;
}

/**
 * Generate HTML that can be converted to PDF
 * In production, this would be rendered by a headless browser
 */
export function generatePDFHTML(options: PDFExportOptions): string {
  const { projections, summary, companyName, scenarioName } = options;

  const lastProjection = projections[projections.length - 1];

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Financial Projection - ${companyName}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      margin: 40px;
      color: #1a1a1a;
    }
    h1 { color: #2563eb; font-size: 28px; margin-bottom: 8px; }
    h2 { color: #1e40af; font-size: 20px; margin-top: 32px; margin-bottom: 16px; }
    .header { border-bottom: 2px solid #2563eb; padding-bottom: 16px; margin-bottom: 32px; }
    .meta { color: #666; font-size: 14px; }
    .metrics-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 24px; }
    .metric-card { border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; }
    .metric-label { font-size: 12px; color: #666; text-transform: uppercase; font-weight: 600; }
    .metric-value { font-size: 24px; font-weight: 700; color: #1a1a1a; margin-top: 4px; }
    .metric-change { font-size: 14px; color: #059669; margin-top: 4px; }
    table { width: 100%; border-collapse: collapse; margin-top: 16px; font-size: 12px; }
    th { background: #f3f4f6; text-align: left; padding: 8px; font-weight: 600; }
    td { padding: 8px; border-bottom: 1px solid #e5e7eb; }
    .footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid #e5e7eb; color: #666; font-size: 12px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>${companyName}</h1>
    <div class="meta">
      Scenario: ${scenarioName} |
      Generated: ${new Date().toLocaleDateString()} |
      Projection Period: ${projections[0].month} to ${lastProjection.month}
    </div>
  </div>

  <h2>Executive Summary</h2>
  <div class="metrics-grid">
    <div class="metric-card">
      <div class="metric-label">Monthly Recurring Revenue</div>
      <div class="metric-value">$${summary.endingMRR.toLocaleString()}</div>
      <div class="metric-change">Growth: ${summary.mrrGrowthPercent.toFixed(1)}%</div>
    </div>
    <div class="metric-card">
      <div class="metric-label">Cash Position</div>
      <div class="metric-value">$${summary.endingCash.toLocaleString()}</div>
      <div class="metric-change">Burned: $${summary.totalCashBurned.toLocaleString()}</div>
    </div>
    <div class="metric-card">
      <div class="metric-label">Peak Monthly Burn</div>
      <div class="metric-value">$${summary.peakBurn.toLocaleString()}</div>
      <div class="metric-change">${summary.peakBurnMonth}</div>
    </div>
    <div class="metric-card">
      <div class="metric-label">Team Size</div>
      <div class="metric-value">${summary.endingHeadcount}</div>
      <div class="metric-change">From ${summary.startingHeadcount} people</div>
    </div>
  </div>

  <h2>Monthly Projections (First 12 Months)</h2>
  <table>
    <thead>
      <tr>
        <th>Month</th>
        <th>MRR</th>
        <th>Revenue</th>
        <th>Total OpEx</th>
        <th>Net Burn</th>
        <th>Cash</th>
        <th>Customers</th>
        <th>Headcount</th>
      </tr>
    </thead>
    <tbody>
      ${projections
        .slice(0, 12)
        .map(
          (p) => `
        <tr>
          <td>${p.month}</td>
          <td>$${p.mrr.toLocaleString()}</td>
          <td>$${p.revenue.toLocaleString()}</td>
          <td>$${p.totalOpex.toLocaleString()}</td>
          <td>$${p.netBurn.toLocaleString()}</td>
          <td>$${p.endingCash.toLocaleString()}</td>
          <td>${Math.round(p.activeCustomers)}</td>
          <td>${p.headcount}</td>
        </tr>
      `
        )
        .join("")}
    </tbody>
  </table>

  <div class="footer">
    Generated by FinModeler | This is a forward-looking projection and should not be considered as a guarantee of future performance.
  </div>
</body>
</html>
  `.trim();
}

/**
 * Stub function for PDF generation
 * In production, this would use puppeteer or a similar library to convert HTML to PDF
 */
export async function generatePDF(options: PDFExportOptions): Promise<Buffer> {
  const html = generatePDFHTML(options);

  // TODO: In production, use puppeteer or similar:
  // const browser = await puppeteer.launch();
  // const page = await browser.newPage();
  // await page.setContent(html);
  // const pdf = await page.pdf({ format: 'A4' });
  // await browser.close();
  // return pdf;

  // For now, return HTML as buffer with a note
  return Buffer.from(
    html +
      "\n\n<!-- Note: This is HTML output. In production, convert to PDF using puppeteer -->"
  );
}
